name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test installer
        run: yes | bash <(curl -s https://raw.githubusercontent.com/akriaueno/dev-env/$GITHUB_SHA/install.sh) # use no chached contents
